// Auto-generated by pb-convert-dw — do not edit
using Microsoft.EntityFrameworkCore;
using ProductCatalog.Application.DTOs;

namespace ProductCatalog.Infrastructure.Data;

public partial class AppDbContext
{
    public DbSet<ProductbrandsDto> Productbrands => Set<ProductbrandsDto>();
}
