// Generated by pb-convert-window (Skill 10) — WMain (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WMain : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;
    [Inject] private ProductCatalog.Blazor.Services.ImageCatalog ImageCatalog { get; set; } = default!;

    protected override void OnInitialized()
    {
        base.OnInitialized();
    }

    // PB: open(w_productfeatures)
    private void OnCbProductfeatures_Clicked() => Navigation.NavigateTo("/productfeatures");

    // PB: open(w_producttypes)
    private void OnCbProducttypes_Clicked() => Navigation.NavigateTo("/producttypes");

    // PB: open(w_productbrands)
    private void OnCbProductbrands_Clicked() => Navigation.NavigateTo("/productbrands");

    // PB: open(w_productitems)
    private void OnCbProductitems_Clicked() => Navigation.NavigateTo("/productitems");

    // PB: open(w_tags)
    private void OnCbTagsWindow_Clicked() => Navigation.NavigateTo("/tags");

    // PB: cb_1.clicked — SQL test query (SELECT Value FROM tags WHERE Id = 2)
    private void OnCb1_Clicked()
    {
        // Original PB used embedded SQL with a separate transaction.
        // In production this would query TagRepository; for now, navigate to windw3.
        Navigation.NavigateTo("/windw3");
    }

    // PB: open(w_productsearch)
    private void OnCbSearch_Clicked() => Navigation.NavigateTo("/productsearch");
}
