// Generated by pb-convert-window (Skill 10) — WProductfeatures (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;
using DW = ProductCatalog.Blazor.Components.DataWindows;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WProductfeatures : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;

    [SupplyParameterFromQuery(Name = "id")]
    public int? Id { get; set; }

    private DW.Productfeatures? _dwProductfeatures;

    protected override void OnInitialized() => base.OnInitialized();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender && Id.HasValue && _dwProductfeatures is not null)
            await _dwProductfeatures.LoadAsync();
    }

    // PB: dw_productfeatures.ScrollNextPage()
    private void OnCbNext_Clicked() => _dwProductfeatures?.OnNext();

    // PB: dw_productfeatures.ScrollPriorPage()
    private void OnCbPrev_Clicked() => _dwProductfeatures?.OnPrev();

    // PB: dw_productfeatures.Update()
    private async Task OnCbUpdate_Clicked()
    {
        if (_dwProductfeatures is not null) await _dwProductfeatures.OnSave();
    }
}
