// Generated by pb-convert-window (Skill 10) — WProducttypes (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;
using DW = ProductCatalog.Blazor.Components.DataWindows;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WProducttypes : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;

    [SupplyParameterFromQuery(Name = "id")]
    public int? Id { get; set; }

    private DW.Producttypes? _dwProducttypes;

    protected override void OnInitialized() => base.OnInitialized();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender && Id.HasValue && _dwProducttypes is not null)
            await _dwProducttypes.LoadAsync();
    }

    // PB: dw_producttypes.ScrollNextPage()
    private void OnCbNext_Clicked() => _dwProducttypes?.OnNext();

    // PB: dw_producttypes.ScrollPriorPage()
    private void OnCbPrev_Clicked() => _dwProducttypes?.OnPrev();

    // PB: dw_producttypes.Update()
    private async Task OnCbUpdate_Clicked()
    {
        if (_dwProducttypes is not null) await _dwProducttypes.OnSave();
    }
}
