// Generated by pb-convert-window (Skill 10) — WProductitems (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;
using DW = ProductCatalog.Blazor.Components.DataWindows;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WProductitems : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;

    [SupplyParameterFromQuery(Name = "id")]
    public int? Id { get; set; }

    private DW.Productitems? _dwProductitems;

    protected override void OnInitialized() => base.OnInitialized();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender && Id.HasValue && _dwProductitems is not null)
            await _dwProductitems.LoadAsync();
    }

    // PB: dw_productitems.ScrollNextRow()
    private void OnCbNext_Clicked() => _dwProductitems?.OnNext();

    // PB: dw_productitems.ScrollPriorPage()
    private void OnCbPrev_Clicked() => _dwProductitems?.OnPrev();

    // PB: dw_productitems.Update()
    private async Task OnCbUpdate_Clicked()
    {
        if (_dwProductitems is not null) await _dwProductitems.OnSave();
    }
}
