// Generated by pb-convert-window (Skill 10) — WProductsearch (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using DW = ProductCatalog.Blazor.Components.DataWindows;
using ProductCatalog.Application.DTOs;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WProductsearch : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;

    private DW.Productsearch? _dwProductsearch;
    private string _sleKeyword = string.Empty;

    protected override void OnInitialized() => base.OnInitialized();

    // PB: cb_search.clicked -> query = sle_keyword.text + '%'; dw_productsearch.retrieve(query)
    private async Task OnSearch()
    {
        if (_dwProductsearch is not null)
            await _dwProductsearch.RetrieveAsync(_sleKeyword);
    }

    private async Task OnSearchKeyUp(KeyboardEventArgs e)
    {
        if (e.Key == "Enter") await OnSearch();
    }

    private void OnRowSelected(ProductsearchDto item) =>
        Navigation.NavigateTo($"/productitems?id={item.ProductitemsId}");

    private void OnRowDoubleClicked(ProductsearchDto item) =>
        Navigation.NavigateTo($"/productitems?id={item.ProductitemsId}");

    // PB: cb_search.clicked — same as OnSearch
    private async Task OnCbSearch_Clicked() => await OnSearch();

    // PB: cb_1.clicked -> dw_productsearch.update()
    private void OnCb1_Clicked()
    {
        Snackbar.Add("Update not available for search results (read-only).", Severity.Info);
    }
}
