// Generated by pb-convert-window (Skill 10) — WProductbrands (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;
using DW = ProductCatalog.Blazor.Components.DataWindows;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WProductbrands : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;

    [SupplyParameterFromQuery(Name = "id")]
    public int? Id { get; set; }

    private DW.Productbrands? _dwProductbrands;

    protected override void OnInitialized() => base.OnInitialized();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender && Id.HasValue && _dwProductbrands is not null)
            await _dwProductbrands.LoadAsync();
    }

    // PB: dw_productbrands.ScrollNextPage()
    private void OnCbNext_Clicked() => _dwProductbrands?.OnNext();

    // PB: dw_productbrands.ScrollPriorPage()
    private void OnCbPrev_Clicked() => _dwProductbrands?.OnPrev();

    // PB: dw_productbrands.Update()
    private async Task OnCbUpdate_Clicked()
    {
        if (_dwProductbrands is not null) await _dwProductbrands.OnSave();
    }
}
