// Generated by pb-convert-window (Skill 10) — WTags (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;
using DW = ProductCatalog.Blazor.Components.DataWindows;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WTags : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;

    [SupplyParameterFromQuery(Name = "id")]
    public int? Id { get; set; }

    private DW.Tag? _dwTag;

    protected override void OnInitialized() => base.OnInitialized();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender && Id.HasValue && _dwTag is not null)
            await _dwTag.LoadAsync();
    }

    // PB: dw_tag.Update()
    private async Task OnCbUpdate_Clicked()
    {
        if (_dwTag is not null) await _dwTag.OnSave();
    }

    // PB: dw_tag.ScrollPriorPage()
    private void OnCbPrev_Clicked() => _dwTag?.OnPrev();

    // PB: dw_tag.ScrollNextPage()
    private void OnCbNext_Clicked() => _dwTag?.OnNext();
}
