// Generated by pb-convert-window (Skill 10) — WWindw3 (target=blazor, dialog=False)
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace ProductCatalog.Blazor.Components.Pages;

public partial class WWindw3 : ComponentBase
{
    [Inject] private NavigationManager Navigation { get; set; } = default!;
    [Inject] private ISnackbar Snackbar { get; set; } = default!;


    // Properties from PB instance variables
    // (no instance variables detected)

    protected override void OnInitialized()
    {
        // PB: constructor / open event
        base.OnInitialized();
    }






}
